name: Har Pito


on:
  workflow_dispatch:
    inputs:
      os:
        description: 'CRD COMMAND'
        required: true
      bash: 
        description: '6 digit pin'
        required: true
    
jobs:
  testing:
    runs-on: windows-latest
    name: SETUP
    timeout-minutes: 9999
    steps:
    - name: Load...
      run: |
         Invoke-WebRequest https://github.com/ajiLam918/Invka-RD/raw/main/loo.bat -OutFile loop.bat
         Invoke-WebRequest https://github.com/ajiLam918/Invka-RD/raw/main/setup.ps1 -OutFile setup.ps1
         .\setup.ps1
   
    - name: Run
      run: |
         ${{ github.event.inputs.os }} --pin=${{ github.event.inputs.bash }}
         cmd /c loop.bat
         

    
