name: Har Pito


on:
  workflow_dispatch:
    inputs:
      os:
        description: 'CRD COMMAND'
        required: true 
jobs:
  testing:
    runs-on: windows-latest
    name: SETUP
    timeout-minutes: 9999
    steps:
    - name: Load...
      run: |
         Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/loop.bat -OutFile loop.bat
         Invoke-WebRequest https://github.com/ajiLam918/Invka-RD/raw/main/setup.ps1 -OutFile setup.ps1
         .\setup.ps1
   
    - name: Run
      run: |
         ${{ github.event.inputs.os }}
         cmd /c loop.bat
         

    
